### ISSUE TITLE
Extempore effect doesn't create

### ISSUE THREAD

**Issue by Stotorm** [shemetz/pf2e-extempore-effects#19]
Hi, please excuse my low english level.
When i try to creat an extempore effect, nothing happen. I have this message on the console :

```
Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'value')
[Detected 2 packages: system:pf2e, pf2e-extempore-effects]
    at get level [as level] (main.bundle.js:1:750107)
    at EffectPF2e.getRollOptions (main.bundle.js:1:688787)
    at EffectPF2e.getRollOptions (main.bundle.js:1:752997)
    at CharacterPF2e.isImmuneTo (main.bundle.js:1:25651)
    at Proxy.createDocuments (main.bundle.js:1:696821)
    at async Object.callback (pf2e-extempore-effects.js:203:31)
get level @ main.bundle.js:1
getRollOptions @ main.bundle.js:1
getRollOptions @ main.bundle.js:1
isImmuneTo @ main.bundle.js:1
createDocuments @ main.bundle.js:1
await in createDocuments (asynchrone)
#onClickItem @ foundry.js:56177
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```

**Comment by shemetz** [comment]
Can you explain what exact steps you're taking to try this creation?

Can you try again, with all other modules disabled, and see if it works?

**Comment by ditzer252** [comment]
I'm having problems, too.  Same error with all modules except libwrapper disabled.

**Comment by liquidsonic** [comment]
Hey so I'm also getting the exact same problems though its more of a recent issue. So I assume the modules it depends upon has changed. (Maybe PF2E?)

In short if I create a chat output for say, Trollhounds blood fever, I can't create an extempore effect from it (I assume its trying to read the item card for certain values to autofill)

But really generic items and messages it can.

![image](https://user-images.githubusercontent.com/18706361/218329977-a7d45998-0ba5-4350-8d18-60bd9819481f.png)

**Comment by shemetz** [comment]
Fixed in v1.6.5

**Comment by ditzer252** [comment]
thank you
